### ISSUE TITLE
Bioportal link broken

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#44]
In https://edamontology.github.io/edam-browser/#format_3620 the link behind bioportal is http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3620 whichis not ~~resolved~~ [Edit] found.

http://edamontology.org/format_3620 is resolved to https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=format_3620

**Comment by matuskalas** [comment]
For me both
http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3620 and
https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=format_3620
work the same.
The first, longer form is the one used internally in BioPortal.

Have I misunderstood the issue then?

**Comment by bryan-brancotte** [comment]
The description was wrong, the first link is resolved, but the page tells me that 
> The page you are looking for wasn't found. Please try again.

as `http%3A%2F%2Fedamontology.org%2F` is redundant with the fact that we are opening edam. This code is [3 years old](https://github.com/IFB-ElixirFr/edam-browser/blame/master/js/tree-edam-stand-alone.js#L344), so maybe the possibilité was removed, or a bug was introduced at the time

**Comment by matuskalas** [comment]
I still don't understand this issue 😕
However, it doesn't look like there is any big problem, so maybe it's not urgent... ?

**Comment by matuskalas** [comment]
ok, works for me in Firefox on Windows, but not on Linux or Android

Please try if this works on your setups: https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http://edamontology.org/format_3620

**Comment by bryan-brancotte** [comment]
> ok, works for me in Firefox on Windows, but not on Linux or Android
> 
> Please try if this works on your setups: https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http://edamontology.org/format_3620

works with chrome+linux in french setup

**Comment by drashti171299** [comment]
@bryan-brancotte @matuskalas  I am not getting what to do in this issue. can you tell me a bit more about it?

**Comment by matuskalas** [comment]
@drashti171299 could you please test which of the following works on your setup (and let us also know your operating system and web browser)?
- http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3620
- https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=format_3620
- https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http://edamontology.org/format_3620

If the last one works for everyone, I'd suggest perhaps using that one in the EDAM Browser code, as it is the same as is used internally in the NCBO BioPortal. Otherwise the second one.
(I personally don't have any strong opinions between option 2 and option 3, the best would probably to ask the BioPortal maintainers which one they recommend | is more future-proof)

**Comment by drashti171299** [comment]
I am working with windows OS and Chrome browser

**Comment by drashti171299** [comment]
from these links, first one is not working for me. 2nd and 3rd are working

**Comment by kellydoleo** [comment]
Out of the below links, the first one doesn't work for me.  It states "The page you are looking for wasn't found. Please try again." The second and third do work. I'm using Chrome on a macOS.

- http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3620
- https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=format_3620
- https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http://edamontology.org/format_3620

**Comment by bryan-brancotte** [comment]
Hi @kellydoleo @drashti171299 

_Here are some explanation on this issue_

The browser is building links to bioportal, but it seems that url parameters are html encoded (`conceptid=http://edamontology.org/format_3620` -> `conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3620`), and then re-encoded (-> `conceptid=http%253A%252F%252Fedamontology.org%252Fformat_3620`)  by the browser/os. The goal here is to find a way that links always work, maybe by not doing the first html encoding, or by simply using the identifier (`conceptid=format_3620`).

Best wishes

**Comment by kellydoleo** [comment]
Hi @bryan-brancotte I was able to figure out the issue I think. Instead of using the identifier which already encodes http://edamontology.org/format_3620, I used the URI. So the URL for bioportal links would now be "https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid="+uri+". Can I have this issue assigned to me? Then I can submit a pull request after committing the changes.

**Comment by HagerDakroury** [comment]
@hmenager, this should be closed since #100 is merged, right?

**Comment by bryan-brancotte** [comment]
You are right @HagerDakroury
